const createUserSessionTable = `
CREATE TABLE USER_SESSIONS (
    SESSION_ID SERIAL PRIMARY KEY,
    USER_ID VARCHAR(100) REFERENCES USERS(USER_ID),
    IS_EXPIRED BOOLEAN DEFAULT FALSE,
    SESSION_TIME DATE DEFAULT (CURRENT_TIMESTAMP + INTERVAL '60 minutes'),
    TOKEN VARCHAR(500)
)
`;
module.exports = createUserSessionTable;
